import assert from "node:assert/strict";
import { suggestionKey, legacySuggestionKey, isCurrentSuggestion, isDismissedSuggestion } from "../src/lib/suggestions.js";
const event = { artist: "SÓLSTAFIR", venue: "APOLO", city: "Barcelona", country: "ES", date: "14/02/2027" };
assert.equal(suggestionKey(event), suggestionKey({ ...event, artist: "solstafir" }));
assert.notEqual(suggestionKey(event), suggestionKey({ ...event, venue: "RAZZMATAZZ" }));
assert(isDismissedSuggestion(event, [legacySuggestionKey(event)]));
assert(isDismissedSuggestion(event, [suggestionKey(event)]));
assert(isCurrentSuggestion(event, new Date(2027, 1, 14, 23)));
assert(!isCurrentSuggestion(event, new Date(2027, 1, 15)));
assert(!isCurrentSuggestion({ ...event, date: "31/02/2027" }, new Date(2027, 0, 1)));
