import React from "react";
import { countryName } from "../lib/countries";
import { useI18n } from "../lib/i18n.jsx";

export default function ConcertDetailPage({ concert, onOpenArtist, onOpenVenue, onOpenCity, onOpenCountry, onOpenSetlist, onEdit, Icon }) {
  const { t, locale } = useI18n();
  if (!concert) return <div className="mx-auto max-w-3xl rounded-3xl border border-zinc-800 bg-zinc-900 px-6 py-16 text-center"><i className="fa-solid fa-ticket mb-4 text-2xl text-zinc-600" aria-hidden="true" /><h2 className="text-xl font-black uppercase text-zinc-100">{t("This concert isn’t available.")}</h2><p className="mt-2 text-sm text-zinc-500">{t("It may have been removed or no longer be in your archive.")}</p></div>;
  const attendees = [...(concert.attendeeUsers || []).filter(({ status }) => status === "confirmed").map(({ displayName, username }) => displayName || username), ...(concert.guestAttendees || [])].filter(Boolean);
  const metadata = [[t("Doors"), concert.doorsAt && new Date(concert.doorsAt).toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" })], [t("Start"), concert.startsAt && new Date(concert.startsAt).toLocaleTimeString(locale, { hour: "2-digit", minute: "2-digit" })], [t("Address"), concert.address], [t("Promoter"), concert.promoter], [t("Festival"), concert.festival], [t("Tour"), concert.tour]].filter(([, value]) => value);
  return <div className="mx-auto max-w-4xl space-y-4">
    <section className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6 md:p-8">
      <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-start"><div className="min-w-0"><button type="button" onClick={() => onOpenArtist(concert.artist)} className="break-words text-left text-3xl font-black uppercase leading-none text-zinc-100 hover:underline">{concert.artist}</button><div className="mt-5 space-y-2"><div className="flex gap-2 text-sm font-semibold text-zinc-200"><Icon type="map" /><button type="button" onClick={() => onOpenVenue(concert.venue)} className="text-left hover:underline">{concert.venue || t("Venue to be confirmed")}</button></div>{concert.city && <div className="flex gap-2 text-sm text-zinc-400"><i className="fa-solid fa-city mt-0.5 w-4 text-center" aria-hidden="true" /><button type="button" onClick={() => onOpenCity(concert)} className="hover:underline">{concert.city}</button>{concert.country && <><span>·</span><button type="button" onClick={() => onOpenCountry(concert.country)} className="hover:underline">{countryName(concert.country, locale)}</button></>}</div>}<div className="flex gap-2 text-sm text-zinc-400"><Icon type="calendar" /><span>{concert.date}</span></div></div></div><div className="flex gap-2">{concert.canEditEvent !== false && <button type="button" onClick={() => onEdit(concert)} className="adn-icon-button" aria-label={t("Edit concert")}><i className="fa-solid fa-pencil" aria-hidden="true" /></button>}<button type="button" onClick={() => onOpenSetlist(concert)} className="adn-button-primary"><Icon type="music" />{t("Setlist")}</button></div></div>
      {concert.eventStatus && concert.eventStatus !== "announced" && <span className="mt-5 inline-flex rounded-lg border border-amber-900 bg-amber-950/30 px-3 py-1.5 text-xs font-black uppercase text-amber-300">{concert.eventStatus.replace("_", " ")}</span>}
    </section>
    {metadata.length > 0 && <section className="grid gap-3 rounded-3xl border border-zinc-800 bg-zinc-900 p-6 sm:grid-cols-2">{metadata.map(([label, value]) => <div key={label}><div className="text-[10px] font-black uppercase tracking-widest text-zinc-600">{label}</div><div className="mt-1 text-sm font-semibold text-zinc-300">{value}</div></div>)}</section>}
    {attendees.length > 0 && <section className="rounded-3xl border border-zinc-800 bg-zinc-900 p-6"><h2 className="text-xs font-black uppercase tracking-widest text-zinc-500">{t("Attended with")}</h2><p className="mt-3 text-base font-semibold text-zinc-200">{attendees.join(" · ")}</p></section>}
    {(concert.ticketUrl || concert.sourceUrl) && <a href={concert.ticketUrl || concert.sourceUrl} target="_blank" rel="noreferrer" className="adn-button-secondary inline-flex">{t("Event and tickets")} <i className="fa-solid fa-arrow-up-right-from-square text-xs" aria-hidden="true" /></a>}
  </div>;
}
