-- Historical one-off personal concert import, already applied.
-- Payload removed from the current tree: user records belong in Supabase.
-- Keep this version placeholder; never replay personal seeds on a fresh project.
